use_frameworks!

platform :ios, '9.0'

target 'SDKMeasurementPlugin_Example' do
  pod 'SDKMeasurementPlugin', :path => '../'

  target 'SDKMeasurementPlugin_Tests' do
    inherit! :search_paths

    
  end
end
